server:
  port: 8081
spring:
  application:
    name: backend
  config:
    import: optional:file:..env[.properties]
  datasource:
    # MySQL 数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://frp.jmdyz.top:3306/health?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: health
    password: zZbtxGGMT4yWGY7r
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true


mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
